image: docker:latest

services:
  - docker:dind

# test:cargo:
#   image: "rustlang/rust:nightly"
#   script:
#     - apt-get update -yqq
#     - apt-get install -yqq --no-install-recommends build-essential
#     - apt-get -y install ca-certificates libssl-dev
#     - rustc --version && cargo --version
#     - cargo test --all --verbose

# build-master:
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive

#   stage: build
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#     - docker push "$CI_REGISTRY_IMAGE"
#   only:
#     - master

deploy_staging:
  image: "rustlang/rust:nightly"
  stage: deploy
  script:
    - ( apt-get update -y && apt-get install ca-certificates openssl openssh-client -y )
    - update-ca-certificates
    - cargo install diesel_cli
    # Configure ssh access key
    - eval $(ssh-agent -s)
    - echo "$STAGING_SERVICE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Setup configuration and data
    - mkdir ~/femapi
    - mkdir ~/femapi/config
    - mkdir ~/femapi/data
    #- echo "$STAGING_DOTENV" | tr -d '\r'> ~/femapi/config/.env
    - export secret=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    - touch ~/femapi/config/env
    - echo "DATABASE_URL = sharefem.db" >> ~/femapi/config/env
    - echo "STATIC_DIR = /www" >> ~/femapi/config/env
    - echo "SECRET = $secret" >> ~/femapi/config/env
    - cp ./Rocket.toml ~/femapi/config
    - cp ./diesel.toml ~/femapi/config
    - diesel setup
    - cp ./sharefem.db ~/femapi/data
    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$STAGING_USER"@"$STAGING_ADDR" rm -rf ~/femapi
    - scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ~/femapi "$STAGING_USER"@"$STAGING_ADDR":~

    - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$STAGING_USER"@"$STAGING_ADDR" docker pull "$CI_REGISTRY_IMAGE"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master
