name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deps
      run: ( apt-get update -y && apt-get install libpq-dev)
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
